name: Nightly Build and Test

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight every day

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Get latest vllm tag
        id: latest-vllm-tag
        run: echo "LATEST_TAG=$(git ls-remote --tags --sort="v:refname" https://github.com/vllm-project/vllm.git | tail -n1 | sed 's/.*\///; s/\^{}//' | sed -e 's/^v//')" >> $GITHUB_OUTPUT
      - name: Update vllm version to latest
        env:
          VLLM_TAG: ${{ steps.latest-vllm-tag.outputs.LATEST_TAG}}
        run: |
          echo $VLLM_TAG
          sed -i -r "s/vllm.git@[^\s]+/vllm.git@v$VLLM_TAG ;/g" pyproject.toml
          sed -i -r "s/vllm>=[^\s]+/vllm>=$VLLM_TAG,<=$VLLM_TAG ; /g" pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r setup_requirements.txt
      - name: Build and test with tox
        run: tox -e py

